export const EMAIL_LOGIN_SUCCESS = 'EMAIL_LOGIN_SUCCESS';
export const EMAIL_LOGIN_FAIL = 'EMAIL_LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ADMIN_MODE_ON = 'ADMIN_MODE_ON';
export const LOGIN_MODAL_OPEN = 'LOGIN_MODAL_OPEN';
export const LOGIN_MODAL_CLOSE = 'LOGIN_MODAL_CLOSE';
